name: Android UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # Checks-out your repository
      - name: Checkout
        uses: actions/checkout@v4

      # Sets up JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Enable KVM
        if: runner.os == 'Linux'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Install cmdline-tools
      - name: Install cmdline-tools
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          mkdir -p ${ANDROID_HOME}/cmdline-tools
          unzip -q cmdline-tools.zip -d ${ANDROID_HOME}/cmdline-tools
          mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest
          export PATH=${ANDROID_HOME}/cmdline-tools/latest/bin:${PATH}

      # Install system image
      - name: Install system image
        run: |
          yes | sdkmanager --licenses > /dev/null
          sdkmanager --install "platforms;android-35" "build-tools;35.0.0" "system-images;android-29;google_apis;x86_64"

      # Create AVD manually
      - name: Create AVD manually
        run: |
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n test -k "system-images;android-29;google_apis;x86_64" -f

      # Run UI tests with emulator
      - name: Run UI tests
        uses: reactivecircus/android-emulator-runner@v2.30.1
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          avd-name: test
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedAndroidTest --no-daemon --max-workers=2 --parallel

      # Upload test reports
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: app/build/reports/androidTests/connected/
          retention-days: 7 # Limit retention to save space
