# This workflow builds artifacts and uploads them to maven central

name: Deploy version

# Controls when the workflow will run
on:
  # This workflow will be launched manually
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Sets up the JDK version
      - name: Set up JDK environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      # Using the key directly from secrets seem to break it. It needs to be decoded from Base54.
      - name: Setup signing
        run: |
          echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 --decode > $RUNNER_TEMP/signing_key.asc
          echo "ORG_GRADLE_PROJECT_signingInMemoryKey=$(cat $RUNNER_TEMP/signing_key.asc | sed -z 's/\n/\\n/g')" >> $GITHUB_ENV

      # Builds artifacts on modules and publishes them to maven central
      - name: Upload artifacts
        run: ./gradlew :core:publishToMavenCentral :compose:publishToMavenCentral :fragment:publishToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
