# This workflow builds artifacts and uploads them to maven central

name: Deploy version

# Controls when the workflow will run
on:
  # This workflow will be launched manually
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Sets up the JDK version
      - name: Set up JDK environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Gradle Cache
        uses: gradle/actions/setup-gradle@v4

      # Setup signing.
      - name: Setup Gradle properties
        run: |
          mkdir -p $HOME/.gradle
          echo "signingInMemoryKeyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" >> $HOME/.gradle/gradle.properties
          echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 --decode | sed -z 's/\n/\\n/g' > $RUNNER_TEMP/key.txt
          echo "signingInMemoryKey=$(cat $RUNNER_TEMP/key.txt)" >> $HOME/.gradle/gradle.properties
          echo "mavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }}" >> $HOME/.gradle/gradle.properties
          echo "mavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}" >> $HOME/.gradle/gradle.properties

      # Builds artifacts on modules and publishes them to maven central
      - name: Upload artifacts
        run: ./gradlew :core:publishToMavenCentral :compose:publishToMavenCentral :fragment:publishToMavenCentral --no-configuration-cache
